services:
  flux-train:
    build: ./
    image: quinninc/flux-train:1.0.0
    container_name: flux-train
    restart: always
    network_mode: "host"
    runtime: nvidia
    env_file: .env
    volumes:
      - ${MOUNT_PATH}:/mnt/fs
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
