services:
  flux-train:
    build: ./
    image: quinninc/flux-train:2.0.0
    container_name: flux-train
    restart: always
    network_mode: "host"
    runtime: nvidia
    privileged: true
    env_file: .env
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
