version: "3.8"
services:
  flux-lora-api:
    build: .
    container_name: flux-lora-api
    restart: always
    volumes:
      - ${OUTPUTS_DIR}:/app/sd-scripts/outputs
      - ${MODELS_DIR}:/app/sd-scripts/models
    network_mode: "host"
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - PORT=3000
